version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  keycloak:

services:

  mariadb:
    image: mariadb:10.1.19
    container_name: keycloak-mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - HOSTNAME=keycloak-mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    networks:
      - keycloak
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "--silent", "--user=$MYSQL_USER", "--password=$MYSQL_PASSWORD"]

  keycloak:
    image: quay.io/keycloak/keycloak:6.0.1
    container_name: keycloak
#    build: server
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
      - 9990:9990
    volumes:
      - ./keycloak/deployments:/opt/jboss/keycloak/standalone/deployments
      - ./resources:/opt/jboss/keycloak/resources
    restart: always
    networks:
      - keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DEBUG=true
      - DEBUG_PORT=8787
      - HOSTNAME=keycloak
    depends_on:
      - mariadb
#    These commands are required to allow remote debugging with docker
    command: ["-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=12345",
              "-Dcom.sun.management.jmxremote.local.only=false", "-Dcom.sun.management.jmxremote.authenticate=false",
              "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.rmi.port=12345",
              "-Djava.rmi.server.hostname=$HOSTNAME",
              "-Dkeycloak.import=/opt/jboss/keycloak/resources/realm-lportal.json",
              "-Dkeycloak.profile.feature.upload_scripts=enabled"]


